# ===================================================================
# Mol-Dorm 认证授权中心 (Auth Service)
# ===================================================================

server:
  # 认证中心通常占用独立端口，建议 9000
  port: 9000
  servlet:
    context-path: /api/auth # 认证中心负责登录、发 Token

spring:
  application:
    # 服务名称，用于后续微服务间的调用标识
    name: mol-auth
  
  # 【核心】导入 common-core 模块中的公共基础配置 (包含数据库、Redis 密码等)
  config:
    import:
      - optional:classpath:/common-base.yml

  # 开启 SpringBoot 3.5 虚拟线程，提升认证接口的并发响应能力
  threads:
    virtual:
      enabled: true

# Sa-Token 针对 Auth 模块的个性化配置
sa-token:
  # Token 风格配置
  token-style: uuid
  # 是否尝试从 Header 读取 Token (前后端分离项目建议开启)
  is-read-header: true
  # 是否尝试 from Cookie 读取 Token
  is-read-cookie: false